AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Order Dispatcher Lambda Function

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  PayPalClientId:
    Type: String
    Description: PayPal Client ID
  PayPalClientSecret:
    Type: String
    Description: PayPal Client Secret
    NoEcho: true
  PayPalMode:
    Type: String
    Default: sandbox
    AllowedValues:
      - sandbox
      - live
  FromEmail:
    Type: String
    Description: Email address for sending notifications
    Default: noreply@example.com

Resources:
  OrderDispatcherFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../shipping-lambda/target/shipping-lambda-1.0-SNAPSHOT.jar
      Handler: com.ecommerce.lambda.OrderDispatcherHandler::handleRequest
      Runtime: java17
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          AWS_REGION: !Ref AWS::Region
          PAYMENT_COMPLETED_TOPIC_ARN: !Ref PaymentCompletedTopic
          PAYMENT_SUSPICIOUS_TOPIC_ARN: !Ref PaymentSuspiciousTopic
          ORDER_STATUS_UPDATED_TOPIC_ARN: !Ref OrderStatusUpdatedTopic
          PAYPAL_CLIENT_ID: !Ref PayPalClientId
          PAYPAL_CLIENT_SECRET: !Ref PayPalClientSecret
          PAYPAL_MODE: !Ref PayPalMode
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PaymentCompletedTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt PaymentSuspiciousTopic.TopicName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt OrderStatusUpdatedTopic.TopicName
      Events:
        OrderUnconfirmedEvent:
          Type: SNS
          Properties:
            Topic: !Ref OrderUnconfirmedTopic

  PaymentCompletedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-PaymentCompleted

  PaymentSuspiciousTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-PaymentSuspicious

  OrderUnconfirmedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-OrderUnconfirmed

  OrderStatusUpdatedTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-OrderStatusUpdated

  OrderReadyForDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-order-ready-for-delivery
      CodeUri: ../shipping-lambda
      Handler: com.ecommerce.lambda.OrderReadyForDeliveryHandler::handleRequest
      Runtime: java17
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ORDER_READY_FOR_DELIVERY_TOPIC_ARN: !Ref OrderReadyForDeliveryTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt OrderReadyForDeliveryTopic.TopicName
      Events:
        PaymentCompletedEvent:
          Type: SNS
          Properties:
            Topic: !Ref PaymentCompletedTopic

  OrderReadyForDeliveryTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-order-ready-for-delivery
      DisplayName: Order Ready For Delivery Topic

  OrderReadyForDeliveryTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sns:Publish
            Resource: !Ref OrderReadyForDeliveryTopic
      Topics:
        - !Ref OrderReadyForDeliveryTopic

  ProcessDeliveryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-process-delivery
      CodeUri: ../shipping-lambda
      Handler: com.ecommerce.lambda.ProcessDeliveryHandler::handleRequest
      Runtime: java17
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          ORDER_STATUS_UPDATED_TOPIC_ARN: !Ref OrderStatusUpdatedTopic
          SHIPPO_API_KEY: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:apiKey}}'
          SHIPPO_FROM_NAME: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromName}}'
          SHIPPO_FROM_STREET: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromStreet}}'
          SHIPPO_FROM_CITY: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromCity}}'
          SHIPPO_FROM_STATE: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromState}}'
          SHIPPO_FROM_ZIP: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromZip}}'
          SHIPPO_FROM_COUNTRY: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromCountry}}'
          SHIPPO_FROM_PHONE: !Sub '{{resolve:secretsmanager:${Environment}/shippo:SecretString:fromPhone}}'
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt OrderStatusUpdatedTopic.TopicName
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${Environment}/shippo-*'
      Events:
        OrderReadyForDeliveryEvent:
          Type: SNS
          Properties:
            Topic: !Ref OrderReadyForDeliveryTopic

  OrderStatusUpdatedTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sns:Publish
            Resource: !Ref OrderStatusUpdatedTopic
      Topics:
        - !Ref OrderStatusUpdatedTopic

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-notification
      CodeUri: ../shipping-lambda
      Handler: com.ecommerce.lambda.NotificationHandler::handleRequest
      Runtime: java17
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Events:
        PaymentCompletedEvent:
          Type: SNS
          Properties:
            Topic: !Ref PaymentCompletedTopic
        OrderStatusUpdatedEvent:
          Type: SNS
          Properties:
            Topic: !Ref OrderStatusUpdatedTopic

Outputs:
  OrderDispatcherFunction:
    Description: Order Dispatcher Lambda Function ARN
    Value: !GetAtt OrderDispatcherFunction.Arn

  PaymentCompletedTopicArn:
    Description: Payment Completed SNS Topic ARN
    Value: !Ref PaymentCompletedTopic

  PaymentSuspiciousTopicArn:
    Description: Payment Suspicious SNS Topic ARN
    Value: !Ref PaymentSuspiciousTopic

  OrderUnconfirmedTopicArn:
    Description: Order Unconfirmed SNS Topic ARN
    Value: !Ref OrderUnconfirmedTopic

  OrderStatusUpdatedTopicArn:
    Description: Order Status Updated SNS Topic ARN
    Value: !Ref OrderStatusUpdatedTopic

  OrderReadyForDeliveryFunction:
    Description: Order Ready For Delivery Lambda Function ARN
    Value: !GetAtt OrderReadyForDeliveryFunction.Arn

  OrderReadyForDeliveryTopic:
    Description: Order Ready For Delivery SNS Topic ARN
    Value: !Ref OrderReadyForDeliveryTopic

  ProcessDeliveryFunction:
    Description: Process Delivery Lambda Function ARN
    Value: !GetAtt ProcessDeliveryFunction.Arn

  NotificationFunction:
    Description: Notification Lambda Function ARN
    Value: !GetAtt NotificationFunction.Arn